package main

import "html/template"

var futuristicDashboardTemplate = template.Must(template.New("dashboard").Parse(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0d0f12"><title>Up</title>
<style>
:root{--bg:#0d0f12;--surface:#15191e;--line:#2a3037;--text:#f0f2ed;--muted:#89928e;--mint:#55e6cb;--red:#ff6e59}*{box-sizing:border-box}body{margin:0;min-height:100svh;color:var(--text);background:var(--bg);font-family:"SFMono-Regular",Consolas,monospace;letter-spacing:0}main{width:min(920px,calc(100% - 40px));margin:auto;padding:28px 0 44px}header{display:flex;align-items:center;justify-content:space-between;padding-bottom:20px;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:12px;font-weight:700}.mark{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--mint);color:var(--mint);font:800 19px Arial}.status{font-size:11px;color:var(--mint)}.layout{display:grid;grid-template-columns:minmax(280px,360px) 1fr;gap:48px;padding:44px 0}.pair h1,.devices h2{margin:0;font:400 34px Georgia,serif;letter-spacing:0}.qr-wrap{width:100%;aspect-ratio:1;margin-top:22px;padding:20px;background:white}.qr{display:block;width:100%;height:100%}.timer{margin-top:12px;color:var(--muted);font-size:11px}.devices-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.count{display:grid;min-width:28px;height:28px;padding:0 8px;place-items:center;background:var(--mint);color:var(--bg);font-size:11px}.device-list{margin:0;padding:0;list-style:none;border-top:1px solid var(--line)}.device{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:13px;align-items:center;min-height:66px;border-bottom:1px solid var(--line)}.device-icon{display:grid;width:34px;height:34px;place-items:center;background:var(--surface);color:var(--mint)}.device-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.device-meta,.empty{margin-top:4px;color:var(--muted);font-size:10px}.empty{padding:28px 0;border-top:1px solid var(--line)}button{min-height:42px;border:1px solid var(--line);background:var(--surface);color:var(--text);font:700 11px inherit;cursor:pointer}button:hover{border-color:var(--mint);color:var(--mint)}.remove{width:42px;padding:0;color:var(--red);font-size:18px}.toolbar{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding-top:20px;border-top:1px solid var(--line)}.danger{color:var(--red)}@media(max-width:700px){main{width:min(100% - 28px,480px)}.layout{grid-template-columns:1fr;gap:42px;padding:34px 0}.pair{max-width:360px;margin:auto;width:100%}.toolbar{grid-template-columns:1fr 1fr}}
</style></head><body><main>
<header><div class="brand"><span class="mark">U</span>UP</div><span class="status">● ONLINE</span></header>
<div class="layout"><section class="pair"><h1>Pair device</h1><div class="qr-wrap"><img class="qr" src="/qr.png" alt="Pairing QR code"></div><div class="timer">ONE-TIME CODE · 10 MIN</div></section><section class="devices"><div class="devices-head"><h2>Devices</h2><span class="count">{{len .Devices}}</span></div>{{if .Devices}}<ul class="device-list">{{range .Devices}}<li class="device"><span class="device-icon">▣</span><div><div class="device-name">{{.Name}}</div><div class="device-meta">{{.Address}} · {{.LastSeen}}</div></div><button class="remove" data-id="{{.ID}}" title="Remove device">×</button></li>{{end}}</ul>{{else}}<div class="empty">No paired devices</div>{{end}}</section></div>
<div class="toolbar"><button id="folder">Open folder</button><button id="rotate">New code</button><button id="revoke">Remove all</button><button class="danger" id="quit">Quit</button></div></main>
<script>const post=p=>fetch(p,{method:'POST'});document.querySelector('#folder').onclick=()=>post('/open-folder');document.querySelector('#rotate').onclick=async()=>{await post('/rotate');location.reload()};document.querySelector('#revoke').onclick=async()=>{if(confirm('Remove all paired devices?')){await post('/revoke');location.reload()}};document.querySelector('#quit').onclick=async()=>{await post('/quit');document.body.innerHTML=''};document.querySelectorAll('.remove').forEach(button=>button.onclick=async()=>{await fetch('/devices/'+button.dataset.id,{method:'DELETE'});location.reload()});setInterval(()=>location.reload(),30000)</script></body></html>`))

var futuristicPhoneTemplate = template.Must(template.New("phone").Parse(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0d0f12"><title>Up</title>
<style>
:root{--bg:#0d0f12;--surface:#15191e;--line:#2a3037;--text:#f0f2ed;--muted:#89928e;--mint:#55e6cb;--red:#ff6e59}*{box-sizing:border-box}body{margin:0;min-height:100svh;color:var(--text);background:var(--bg);font-family:"SFMono-Regular",Consolas,monospace;letter-spacing:0}main{width:min(640px,100%);margin:auto;padding:22px 18px 60px}header{display:flex;align-items:center;justify-content:space-between;padding-bottom:18px;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:10px;font-weight:700}.mark{width:32px;height:32px;display:grid;place-items:center;border:1px solid var(--mint);color:var(--mint);font:800 18px Arial}.status{font-size:10px;color:var(--mint)}nav{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid var(--line)}nav button{height:52px;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--muted);font:700 12px inherit;cursor:pointer}nav button.active{border-color:var(--mint);color:var(--text)}section{display:none;padding-top:26px}section.active{display:block}h1{margin:0 0 20px;font:400 30px Georgia,serif;letter-spacing:0}input[type=file]{position:absolute;width:1px;height:1px;opacity:0}.picker{min-height:220px;display:grid;place-items:center;padding:28px;border:1px dashed #455057;background:var(--surface);text-align:center;cursor:pointer}.upload-icon{display:grid;width:52px;height:52px;margin:0 auto 14px;place-items:center;border:1px solid var(--line);color:var(--mint);font-size:26px}.picker strong{display:block;font:400 18px Georgia,serif}.detail,.meta,.empty,#notice{font-size:11px;color:var(--muted)}#send-button{width:100%;min-height:50px;margin-top:10px;border:0;background:var(--mint);color:var(--bg);font:800 11px inherit;cursor:pointer}.progress{height:2px;background:var(--line)}.progress span{display:block;width:0;height:100%;background:var(--mint)}#notice{min-height:18px;margin-top:10px;color:var(--mint)}.files{margin:0;padding:0;list-style:none;border-top:1px solid var(--line)}.file{display:grid;grid-template-columns:minmax(0,1fr) 42px {{if .AllowDelete}}42px{{end}};gap:10px;align-items:center;min-height:64px;border-bottom:1px solid var(--line)}.name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.meta{margin-top:4px}.icon,.delete{display:grid;width:42px;height:42px;place-items:center;border:1px solid var(--line);background:transparent;color:var(--mint);text-decoration:none;font-size:20px}.delete{color:var(--red)}.empty{padding:28px 0}
</style></head><body><main>
<header><div class="brand"><span class="mark">U</span>UP</div><span class="status">● PAIRED</span></header><nav><button class="tab active" data-tab="send">Send</button><button class="tab" data-tab="files">Files</button></nav>
<section id="send" class="active"><h1>Send files</h1><form id="upload"><label class="picker"><input id="picker" type="file" name="files" multiple required><span><span class="upload-icon">↑</span><strong id="selection">Choose files</strong><span class="detail">Tap to browse</span></span></label><button id="send-button" type="submit">Send</button><div class="progress"><span id="progress"></span></div></form><div id="notice" role="status"></div></section>
<section id="files"><h1>Files</h1><div id="listing" class="empty">Loading…</div></section></main>
<script>const input=document.querySelector('#picker'),form=document.querySelector('#upload'),send=document.querySelector('#send-button'),notice=document.querySelector('#notice'),listing=document.querySelector('#listing'),progress=document.querySelector('#progress'),allowDelete={{.AllowDelete}};document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab,section').forEach(el=>el.classList.remove('active'));tab.classList.add('active');document.querySelector('#'+tab.dataset.tab).classList.add('active')});const size=b=>b<1024?b+' B':b<1048576?(b/1024).toFixed(1)+' KB':b<1073741824?(b/1048576).toFixed(1)+' MB':(b/1073741824).toFixed(1)+' GB';const esc=v=>v.replace(/[&<>']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;'}[c]));input.onchange=()=>document.querySelector('#selection').textContent=input.files.length?input.files.length+' selected':'Choose files';async function load(){const response=await fetch('/app/api/files');if(!response.ok)throw Error('Pair again');const files=await response.json();listing.className=files.length?'':'empty';listing.innerHTML=files.length?'<ul class="files">'+files.map(file=>{const name=esc(file.name),path=encodeURIComponent(file.name);return '<li class="file"><div><div class="name">'+name+'</div><div class="meta">'+size(file.size)+'</div></div><a class="icon" href="/app/files/'+path+'" download title="Download">↓</a>'+(allowDelete?'<button class="delete" data-name="'+name+'">×</button>':'')+'</li>'}).join('')+'</ul>':'No files'}form.onsubmit=event=>{event.preventDefault();if(!input.files.length)return;send.disabled=true;const xhr=new XMLHttpRequest();xhr.open('POST','/app/api/upload');xhr.upload.onprogress=e=>{if(e.lengthComputable)progress.style.width=e.loaded/e.total*100+'%'};xhr.onload=async()=>{notice.textContent=xhr.status<300?'Sent':'Failed';send.disabled=false;form.reset();input.onchange();await load();setTimeout(()=>progress.style.width='0',600)};xhr.onerror=()=>{notice.textContent='Failed';send.disabled=false};xhr.send(new FormData(form))};listing.onclick=async event=>{const button=event.target.closest('.delete');if(!button)return;await fetch('/app/files/'+encodeURIComponent(button.dataset.name),{method:'DELETE'});load()};load().catch(error=>listing.textContent=error.message);setInterval(()=>load().catch(()=>{}),3000)</script></body></html>`))
